name:                ifs
version:             0.1.0.0
github:              "fpclass/ifs"
license:             MIT
author:              "Michael B. Gale and Oscar Harris"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright (c) Michael B. Gale and Oscar Harris"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Implementation of the IFS timetabling algorithm in Haskell

dependencies:
- base >= 4.7 && < 5
- containers
- random
- transformers
- unordered-containers
- hashable

default-extensions:
- RecordWildCards

library:
  source-dirs: src

tests:
  ifs-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ifs
